import { test, expect, type Page } from '@playwright/test';
test.use({ baseURL: 'http://127.0.0.1:3100' });
async function seek(page: Page, id: string, p: number) {
  await page.locator(`#${id}`).evaluate((el, progress) => {
    const s = el as HTMLElement;
    scrollTo(0, Number(s.dataset.scrollStart) + progress * (Number(s.dataset.scrollEnd) - Number(s.dataset.scrollStart)));
  }, p);
  await page.waitForTimeout(850);
}
test('1440 refinement journey, media, continuous river, photo interactions and reverse', async ({ page, context }) => {
  test.setTimeout(180000);
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
  page.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
  await page.goto('/#intro');
  await expect(page.locator('#__ulsan-story')).toHaveAttribute('data-scroll-ready', 'true');
  await page.waitForTimeout(1000);
  await expect(page.locator('#upper-stream')).toHaveAttribute('data-pinned', 'true');
  await expect(page.locator('[data-motion-toggle]')).toHaveCount(0);
  const chapters = page.locator('summary').filter({ hasText: 'CHAPTERS' });
  await expect(chapters).toHaveCSS('border-top-width','0px');
  await expect(chapters).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
  await seek(page, 'intro', .6);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-ulsan.png' });
  await seek(page, 'intro', .9);
  await expect(page.locator('[data-intro-video]')).toHaveCSS('opacity', '1');
  await expect(page.locator('#intro [data-scene-copy]')).toHaveCSS('opacity', '0');
  await expect(page.locator('[data-upper-video]')).toHaveCount(0);
  const video = page.locator('[data-transition-video]');
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThan(1);
  expect(await video.evaluate(v => (v as HTMLVideoElement).videoWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-video.png' });
  await seek(page,'source',.3);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-source.png' });
  await seek(page, 'history', .4);
  await expect(video).toHaveJSProperty('paused', true);
  await seek(page, 'industry', .98);
  await seek(page, 'dead-river', .3);
  const photo = page.locator('#dead-river [data-asset-id="past-taehwa-3"]');
  expect((await photo.boundingBox())!.width).toBeGreaterThan(1400);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-dead.png' });
  await seek(page, 'dead-river', .66);
  await expect(page.locator('[data-bod-fact]')).toContainText('1996 · BOD 11.3 mg/L');
  await expect(page.locator('[data-bod-fact]')).toContainText('생화학적 산소요구량');
  expect(Number(await page.locator('[data-dead-archive]').evaluate(el => getComputedStyle(el).opacity))).toBeGreaterThan(.3);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-bod.png' });
  await seek(page, 'dead-river', .98);
  const river = page.locator('[data-continuous-river]');
  const before = Number(await river.locator('path').evaluate(el => (el as SVGElement).style.strokeDashoffset));
  await seek(page, 'recovery', .03);
  await expect(river).toBeVisible();
  const after = Number(await river.locator('path').evaluate(el => (el as SVGElement).style.strokeDashoffset));
  expect(after).toBeLessThan(before);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-river-seam.png' });
  for (const p of [.1,.25,.39,.53,.67,.81,.9]) await seek(page, 'recovery', p);
  await seek(page, 'garden', .26);
  await seek(page, 'garden', .9);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-bamboo.png' });
  await seek(page, 'whale', .55);
  await expect(page.locator('#whale canvas, #whale svg')).toHaveCount(0);
  const whaleVideo = page.locator('[data-whale-motion-video]');
  await expect.poll(() => whaleVideo.evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThan(1);
  await expect(whaleVideo).toHaveAttribute('src', /%EA%B3%A0%EB%9E%98/);
  const whaleTime = await whaleVideo.evaluate(v => (v as HTMLVideoElement).currentTime);
  await seek(page, 'whale', .8);
  expect(await whaleVideo.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(whaleTime);
  await seek(page, 'whale', .55);
  await expect(page.locator('[data-whale-follow]')).toHaveCount(0);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-whale.png' });
  await seek(page, 'jangsaengpo', .3);
  await expect(page.locator('[data-whale-video]')).toBeVisible();
  await page.screenshot({ path: '.tools/refinement45-qa/1440-crossing.png' });
  await seek(page, 'jangsaengpo', .65);
  await expect(page.locator('[data-jang-title]')).toHaveCSS('opacity', '1');
  await expect(page.locator('[data-jang-memory]')).toHaveCount(0);
  const jang = page.locator('#jangsaengpo [data-photo-link]');
  const jangBox = await jang.boundingBox();
  expect(jangBox!.width).toBeGreaterThan(1400);
  await page.mouse.move(900, 400);
  await expect(page.locator('[data-global-ripple]')).toBeVisible();
  await page.mouse.move(935, 430);
  await expect.poll(() => page.locator('[data-global-ripple]').getAttribute('data-responses')).not.toBeNull();
  await expect(page.locator('[aria-hidden="true"] span').filter({ hasText: '+ MORE' }).last()).toBeVisible();
  await page.screenshot({ path: '.tools/refinement45-qa/1440-ripple-more.png' });
  await page.mouse.move(10, 10);
  await jang.focus();
  await expect(jang).toBeFocused();
  const href = await jang.getAttribute('href');
  await context.route(href!, route => route.fulfill({ status: 200, body: 'Link destination verified' }));
  const popup = page.waitForEvent('popup');
  await page.keyboard.press('Enter');
  const destination = await popup;
  await destination.waitForLoadState();
  expect(destination.url()).toBe(href);
  await destination.close();
  await page.screenshot({ path: '.tools/refinement45-qa/1440-jangsaengpo.png' });
  await seek(page, 'sea', .35);
  await expect(page.locator('[data-whale-video]')).toBeHidden();
  await expect(whaleVideo).toHaveJSProperty('paused',true);
  await page.screenshot({ path: '.tools/refinement45-qa/1440-port.png' });
  for (const id of ['ending','night','explore','sea','jangsaengpo','whale','garden','recovery','dead-river','industry','history','upper-stream','source','intro']) {
    await seek(page, id, .6);
    const before = Number(await page.locator('[data-global-ripple]').getAttribute('data-responses'));
    await page.mouse.move(420,320); await page.waitForTimeout(50); await page.mouse.move(550,370);
    await expect.poll(async()=>Number(await page.locator('[data-global-ripple]').getAttribute('data-responses'))).toBeGreaterThan(before);
  }
  await seek(page,'whale',.55);
  await expect(whaleVideo).toHaveJSProperty('paused', false);
  expect(await page.locator('canvas').evaluateAll(nodes => nodes.filter(n => !n.hasAttribute('data-global-ripple')).length)).toBeLessThanOrEqual(1);
  await page.mouse.wheel(0, 7000); await page.waitForTimeout(1200);
  await page.mouse.wheel(0, -7000); await page.waitForTimeout(1200);
  await page.locator('summary').filter({ hasText: 'CHAPTERS' }).click();
  await page.locator('details a[href="#recovery"]').click();
  await expect(page.locator('#recovery-heading')).toBeFocused();
  await expect(river).toBeVisible();
  await seek(page,'dead-river',.66);
  await page.reload();
  await expect(page.locator('#__ulsan-story')).toHaveAttribute('data-scroll-ready','true');
  await expect(page.locator('[data-bod-fact]')).toHaveCSS('opacity','1');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.body.scrollWidth <= innerWidth)).toBe(true);
  expect(await page.locator('body').innerText()).not.toMatch(/공식 정보|Official Information|자세히 보기|View Details/);
  expect(errors).toEqual([]);
});
for (const width of [1280,1600,1920]) test(`layout ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1280 ? 720 : 900 });
  await page.goto('/#jangsaengpo');
  await expect(page.locator('#__ulsan-story')).toHaveAttribute('data-scroll-ready', 'true');
  await seek(page,'jangsaengpo',.65);
  for (const selector of ['[data-jang-title]','[data-title-ko]','[data-body-ko]','[data-body-en]']) {
    const rect = await page.locator(`#jangsaengpo ${selector}`).boundingBox();
    expect(rect!.x).toBeGreaterThanOrEqual(0); expect(rect!.x+rect!.width).toBeLessThanOrEqual(width);
    expect(rect!.y).toBeGreaterThanOrEqual(0); expect(rect!.y+rect!.height).toBeLessThanOrEqual(width === 1280 ? 720 : 900);
  }
  await page.screenshot({ path: `.tools/refinement45-qa/${width}-jangsaengpo.png` });
  await seek(page,'dead-river',.66);
  await page.screenshot({ path: `.tools/refinement45-qa/${width}-bod.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.body.scrollWidth <= innerWidth)).toBe(true);
});
test('system reduced motion keeps content and semantic photo links', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/#dead-river');
  await expect(page.locator('#__ulsan-story')).toHaveAttribute('data-motion-profile','reduced');
  await expect(page.locator('.pin-spacer')).toHaveCount(0);
  await expect(page.locator('[data-motion-toggle]')).toHaveCount(0);
  await expect(page.locator('canvas')).toHaveCount(0);
  await expect(page.locator('[data-transition-video]')).toHaveAttribute('preload','none');
  expect(await page.locator('[data-transition-video]').getAttribute('src')).toBeNull();
  const link=page.locator('#dead-river [data-photo-link]');
  await link.focus(); await expect(link).toBeFocused();
  await page.mouse.move(500,500); await expect(page.locator('canvas')).toHaveCount(0);
  await expect(page.locator('[data-bod-fact]')).toContainText('생화학적 산소요구량');
});
